## Regenerates R/reserved.R: every name that montest()/seqtest() code uses inside a data.table
## `[ ]` call (i, j, by) or as a `:=` target. A user column with one of these names would be
## resolved instead of (or be overwritten by) the package's own variable/column, so montest()
## aliases such columns internally (see alias_collisions()). Run from the package root:
##   Rscript data-raw/reserved_names.R
suppressMessages(pkgload::load_all(".", quiet = TRUE))
ns <- asNamespace("montest")
fns <- Filter(is.function, mget(setdiff(ls(ns, all.names = TRUE), ".mt_reserved"), envir = ns))
hits <- character()
walk <- function(e) {
  if (is.call(e)) {
    h <- e[[1L]]
    if (is.symbol(h) && as.character(h) == "[" && length(e) >= 4L) {
      for (a in as.list(e)[-(1:2)]) if (!missing(a)) hits <<- c(hits, all.vars(a))
    }
    if (is.symbol(h) && as.character(h) == ":=" && length(e) == 3L) {
      lhs <- e[[2L]]
      hits <<- c(hits, all.vars(lhs), if (is.character(lhs)) lhs)
      if (is.call(lhs)) for (a in as.list(lhs)) if (is.character(a)) hits <<- c(hits, a)
    }
    for (a in as.list(e)) if (!missing(a)) walk(a)
  }
}
for (f in fns) walk(body(f))
## also string literals assigned as new columns, e.g. data[, "Q.hat" := ...] / paste0(Z, ".hat")
lits <- unlist(lapply(c("R/montest.R", "R/functions.R", "R/seqtest.R"), function(p) {
  m <- regmatches(readLines(p), gregexpr('"[A-Za-z][A-Za-z0-9_.]*"', readLines(p)))
  gsub('"', "", unlist(m))
}))
internal_cols <- c("Q", "Q.hat", "sample", "zmargin", "dval", "yval", "condition", "equation", "block", "id_",
                   "scores", "scores_v", "pred", "pred_o", "w_eff", "linear", "Avals", "cf_fold")
nm <- sort(unique(c(hits, internal_cols)))
nm <- nm[!grepl("^[.]", nm) & nzchar(nm) & make.names(nm) == nm]
writeLines(c(
  "## Generated by data-raw/reserved_names.R -- do not edit by hand.",
  "## Names used inside data.table `[ ]` calls / as `:=` targets in the package; montest() aliases",
  "## user columns with these names internally (see alias_collisions()).",
  paste0(".mt_reserved <- c(", paste(sprintf('"%s"', nm), collapse = ", "), ")")
), "R/reserved.R")
cat(length(nm), "names written to R/reserved.R\n")
